"""Bounded local training and GPU smoke-test utilities."""

from .adapters import (
    AstroMambaHTrainingAdapter,
    AstroMambaHTrainingBatch,
    TinyAstroAdapter,
    TinyAstroAdapterBatch,
    make_tiny_adapter_batch,
    make_tiny_astromamba_batch,
    tiny_astromamba_config,
)
from .harness import (
    BoundedTrainer,
    CheckpointReport,
    EpochReport,
    NonFiniteTrainingError,
    TrainingConfig,
    TrainingState,
    DEFAULT_RSS_CAP_BYTES,
    DEFAULT_STORAGE_CAP_BYTES,
    amp_supported,
    default_loss_fn,
    event_only_loss_fn,
    source_event_loss_fn,
    process_rss_bytes,
    resolve_device,
)
from .cache import (
    DEFAULT_MAX_CACHE_BYTES,
    DEFAULT_MAX_ENTRY_BYTES,
    MAX_CACHE_ENTRIES,
    ProceduralSyntheticCache,
)
from .synthetic import (
    iter_paired_synthetic_training_batches,
    iter_parented_synthetic_training_batches,
    iter_synthetic_training_batches,
)
from .pipeline import (
    CurriculumGateReport,
    DEFAULT_SYNTHETIC_CACHE_DIR,
    DEFAULT_SYNTHETIC_CACHE_SIZE_MIB,
    DEFAULT_SYNTHETIC_MIN_EXAMPLES,
    EvaluationReport,
    PhaseReport,
    evaluate_parent_injections,
    evaluate_unlabeled,
    train_synthetic_then_real,
)

__all__ = [
    "BoundedTrainer",
    "DEFAULT_RSS_CAP_BYTES",
    "DEFAULT_STORAGE_CAP_BYTES",
    "AstroMambaHTrainingAdapter",
    "AstroMambaHTrainingBatch",
    "CheckpointReport",
    "EpochReport",
    "NonFiniteTrainingError",
    "TinyAstroAdapter",
    "TinyAstroAdapterBatch",
    "TrainingConfig",
    "TrainingState",
    "amp_supported",
    "default_loss_fn",
    "event_only_loss_fn",
    "source_event_loss_fn",
    "iter_synthetic_training_batches",
    "iter_parented_synthetic_training_batches",
    "iter_paired_synthetic_training_batches",
    "CurriculumGateReport",
    "DEFAULT_SYNTHETIC_CACHE_DIR",
    "DEFAULT_SYNTHETIC_CACHE_SIZE_MIB",
    "DEFAULT_SYNTHETIC_MIN_EXAMPLES",
    "MAX_CACHE_ENTRIES",
    "DEFAULT_MAX_CACHE_BYTES",
    "DEFAULT_MAX_ENTRY_BYTES",
    "ProceduralSyntheticCache",
    "EvaluationReport",
    "PhaseReport",
    "evaluate_parent_injections",
    "evaluate_unlabeled",
    "train_synthetic_then_real",
    "make_tiny_adapter_batch",
    "make_tiny_astromamba_batch",
    "process_rss_bytes",
    "resolve_device",
    "tiny_astromamba_config",
]
