"""Build a provenance-preserving corpus from real Kepler target-pixel files.

The positive examples are windows around published Kepler DR25 confirmed-planet
ephemerides in actual MAST Target Pixel Files.  Each positive is paired with an
off-transit control window from the same TPF; neither side is generated by an
injection simulator.  Raw TPFs are temporary and are removed after extraction.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import gzip
import hashlib
import json
import math
import os
import re
import tempfile
import time
from concurrent.futures import Future, ThreadPoolExecutor, as_completed
from pathlib import Path
from urllib.parse import urljoin
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

import numpy as np
from astropy.io import fits
from astropy.time import Time


BASE_URL = "https://archive.stsci.edu/pub/kepler/target_pixel_files/"
TPF_RE = re.compile(r'href=["\']([^"\']+_([ls])pd-targ\.fits\.gz)["\']', re.I)


def _get(url: str, *, timeout: int = 60, attempts: int = 4) -> bytes:
    """Read a MAST object with bounded retries and no unbounded buffering loop."""
    last_error: Exception | None = None
    for attempt in range(attempts):
        request = Request(url, headers={"User-Agent": "planets-hubble-real-transit-builder/1"})
        try:
            with urlopen(request, timeout=timeout) as response:  # noqa: S310 - fixed MAST URL roots
                chunks: list[bytes] = []
                while True:
                    chunk = response.read(1024 * 1024)
                    if not chunk:
                        break
                    chunks.append(chunk)
                return b"".join(chunks)
        except (HTTPError, URLError, TimeoutError, OSError) as exc:
            last_error = exc
            if attempt + 1 < attempts:
                time.sleep(min(2.0**attempt, 8.0))
    raise RuntimeError(f"MAST download failed after {attempts} attempts: {url}: {last_error}") from last_error


def _download(url: str, destination: Path, *, timeout: int = 180) -> None:
    """Download atomically so an interrupted FITS transfer cannot be parsed as data."""
    if destination.is_file() and destination.stat().st_size > 0:
        return
    partial = destination.with_suffix(destination.suffix + ".part")
    partial.unlink(missing_ok=True)
    payload = _get(url, timeout=timeout)
    partial.write_bytes(payload)
    partial.replace(destination)


def _catalog_rows(path: Path) -> list[dict[str, str]]:
    with gzip.open(path, "rt", encoding="utf-8", newline="") as handle:
        rows = [row for row in csv.DictReader(handle, delimiter="\t") if row["koi_disposition"] == "CONFIRMED"]
    # One planet per host gives a more independent host split than repeatedly
    # taking planets from the same crowded system.
    selected: list[dict[str, str]] = []
    seen_hosts: set[str] = set()
    for row in rows:
        host = row["kepid"]
        if host in seen_hosts:
            continue
        try:
            period = float(row["koi_period"])
            epoch = float(row["koi_time0bk"])
            duration_hours = float(row["koi_duration"])
            if not all(math.isfinite(value) for value in (period, epoch, duration_hours)):
                continue
            if period <= 0.0 or duration_hours <= 0.0:
                continue
        except (TypeError, ValueError):
            continue
        seen_hosts.add(host)
        selected.append(row)
    return selected


def _listing(kepid: int, cache_dir: Path) -> list[str]:
    cache = cache_dir / f"{kepid:09d}.json"
    if cache.is_file():
        return json.loads(cache.read_text(encoding="utf-8"))
    padded = f"{kepid:09d}"
    url = urljoin(BASE_URL, f"{padded[:4]}/{padded}/")
    body = _get(url)
    names = sorted({match.group(1) for match in TPF_RE.finditer(body.decode("utf-8", errors="replace"))})
    cache.write_text(json.dumps(names, indent=2), encoding="utf-8")
    return names


def _file_start_bkjd(name: str) -> float | None:
    match = re.search(r"-(\d{13})_", name)
    if match is None:
        return None
    stamp = match.group(1)
    try:
        year = int(stamp[:4])
        day = int(stamp[4:7])
        hour = int(stamp[7:9])
        minute = int(stamp[9:11])
        second = int(stamp[11:13])
        value = dt.datetime(year, 1, 1, hour, minute, second, tzinfo=dt.timezone.utc) + dt.timedelta(days=day - 1)
        return float(Time(value, scale="utc").tdb.jd - 2454833.0)
    except (ValueError, OverflowError):
        return None


def _rank_tpf_names(names: list[str], epoch: float) -> list[str]:
    scored: list[tuple[float, str]] = []
    for name in names:
        start = _file_start_bkjd(name)
        if start is None:
            continue
        distance = abs((start + 45.0) - epoch)
        scored.append((distance, name))
    return [name for _, name in sorted(scored)]


def _load_tpf(path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, dict[str, object]]:
    with fits.open(path, memmap=False) as hdul:
        table = hdul[1].data
        header = hdul[0].header
        times = np.asarray(table["TIME"], dtype=np.float64)
        flux = np.asarray(table["FLUX"], dtype=np.float32)
        flux_err = np.asarray(table["FLUX_ERR"], dtype=np.float32)
        # Kepler TPFs carry the estimated per-pixel sky/background in a
        # separate FLUX_BKG column.  Remove it before materialising the
        # science plane; otherwise a summed aperture is dominated by sky
        # counts and shallow transit depths are diluted substantially.
        if "FLUX_BKG" in table.names:
            background = np.asarray(table["FLUX_BKG"], dtype=np.float32)
            flux = flux - np.where(np.isfinite(background), background, 0.0)
        raw = np.asarray(table["RAW_CNTS"], dtype=np.float32)
        quality = np.asarray(table["QUALITY"], dtype=np.int32)
        if not np.isfinite(flux).any():
            flux = raw
        metadata = {
            "object": str(header.get("OBJECT", "")),
            "kepid": int(header.get("KEPLERID", 0)),
            "quarter": int(header.get("QUARTER", -1)),
            "channel": int(header.get("CHANNEL", -1)),
            "module": int(header.get("MODULE", -1)),
            "output": int(header.get("OUTPUT", -1)),
            "ra": float(header.get("RA_OBJ", float("nan"))),
            "dec": float(header.get("DEC_OBJ", float("nan"))),
            "cadence_seconds": float(header.get("TIMEDEL", 0.02043365)) * 86400.0,
            "rows": int(flux.shape[1]),
            "cols": int(flux.shape[2]),
        }
    return times, flux, flux_err, quality, metadata


def _window(
    times: np.ndarray,
    flux: np.ndarray,
    flux_err: np.ndarray,
    quality: np.ndarray,
    center: float,
    duration_hours: float,
    *,
    frames: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray] | None:
    half = max(duration_hours / 24.0 * 2.5, frames * 0.0204 / 2.0)
    valid = np.isfinite(times) & (times >= center - half) & (times <= center + half)
    indices = np.flatnonzero(valid)
    if len(indices) < frames:
        return None
    nearest = int(indices[np.argmin(np.abs(times[indices] - center))])
    start = nearest - frames // 2
    stop = start + frames
    if start < 0 or stop > len(times):
        return None
    selected_times = times[start:stop]
    if not np.isfinite(selected_times).all():
        return None
    selected_flux = flux[start:stop]
    selected_err = flux_err[start:stop]
    selected_quality = quality[start:stop]
    if not np.isfinite(selected_flux).any():
        return None
    return selected_times, selected_flux, selected_err, selected_quality


def _window_metrics(payload: tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]) -> dict[str, float | int]:
    """Summarize the observed pixel window without turning it into a synthetic label."""
    times, flux, flux_err, quality = payload
    cadence_flux = np.nansum(np.where(np.isfinite(flux), flux, 0.0), axis=(1, 2))
    finite_cadences = np.isfinite(cadence_flux) & (cadence_flux > 0.0)
    if finite_cadences.sum() < 4:
        return {
            "finite_cadences": int(finite_cadences.sum()),
            "median_aperture_flux": float("nan"),
            "normalized_scatter": float("nan"),
            "quality_nonzero_cadences": int(np.count_nonzero(quality)),
        }
    values = cadence_flux[finite_cadences]
    median = float(np.median(values))
    scatter = float(np.median(np.abs(values - median)) / max(abs(median), 1e-12))
    return {
        "finite_cadences": int(finite_cadences.sum()),
        "median_aperture_flux": median,
        "normalized_scatter": scatter,
        "quality_nonzero_cadences": int(np.count_nonzero(quality)),
        "time_start_bkjd": float(np.nanmin(times)),
        "time_end_bkjd": float(np.nanmax(times)),
    }


def _split_for_host(kepid: int) -> str:
    """Stable host split; all planets/windows from a host stay in one partition."""
    bucket = int(hashlib.sha256(str(kepid).encode("ascii")).hexdigest()[:8], 16) % 100
    if bucket < 80:
        return "train"
    if bucket < 90:
        return "validation"
    return "test"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _write_example(
    path: Path,
    *,
    times: np.ndarray,
    flux: np.ndarray,
    flux_err: np.ndarray,
    quality: np.ndarray,
    label: int,
    metadata: dict[str, object],
) -> None:
    finite = np.isfinite(flux)
    # Kepler RAW_CNTS/FLUX values commonly exceed float16's 65,504 maximum.
    # Keep detector values in float32 so acquisition never silently overflows.
    cleaned_flux = np.nan_to_num(flux, nan=0.0, posinf=0.0, neginf=0.0).astype(np.float32)
    cleaned_err = np.nan_to_num(np.abs(flux_err), nan=0.0, posinf=0.0, neginf=0.0).astype(np.float32)
    np.savez_compressed(
        path,
        time=times.astype(np.float64),
        science=cleaned_flux,
        uncertainty=cleaned_err,
        quality=quality.astype(np.int32),
        finite=finite.astype(np.uint8),
        label=np.asarray(label, dtype=np.int8),
        source_kepid=np.asarray(int(metadata["kepid"]), dtype=np.int64),
        source_tpf=np.asarray(str(metadata["tpf_url"])),
    )


def _acquire_candidate(
    row: dict[str, str],
    *,
    cache_dir: Path,
    raw_dir: Path,
    keep_tpf: bool,
    frames: int,
) -> tuple[dict[str, str], tuple[str, str, tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray], tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray], dict[str, object], float, float]]:
    """Acquire one host without touching the shared manifest or example index."""
    kepid = int(row["kepid"])
    period = float(row["koi_period"])
    epoch = float(row["koi_time0bk"])
    duration_hours = float(row["koi_duration"])
    names = _listing(kepid, cache_dir)
    ranked_names = _rank_tpf_names(names, epoch)
    if not ranked_names:
        raise RuntimeError("no timestamped target-pixel file")
    padded = f"{kepid:09d}"
    selected = None
    last_reason = "no candidate TPF contained both windows"
    for tpf_name in ranked_names:
        tpf_url = urljoin(BASE_URL, f"{padded[:4]}/{padded}/{tpf_name}")
        if keep_tpf:
            raw_path = raw_dir / tpf_name
        else:
            fd, temporary_name = tempfile.mkstemp(prefix="kepler-", suffix=".fits.gz", dir=raw_dir.parent)
            os.close(fd)
            raw_path = Path(temporary_name)
        try:
            _download(tpf_url, raw_path, timeout=180)
            times, flux, flux_err, quality, tpf_metadata = _load_tpf(raw_path)
        except Exception as exc:
            last_reason = str(exc)
            continue
        finally:
            if not keep_tpf:
                raw_path.unlink(missing_ok=True)
        if not np.isfinite(times).any():
            last_reason = "TPF contains no finite cadence times"
            continue
        positive_center = epoch + round((float(np.nanmedian(times)) - epoch) / period) * period
        positive = _window(times, flux, flux_err, quality, positive_center, duration_hours, frames=frames)
        if positive is None:
            last_reason = "TPF lacks enough cadences around a published transit epoch"
            continue
        negative = None
        negative_center = 0.0
        for possible_center in (positive_center + period / 2.0, positive_center - period / 2.0):
            negative = _window(times, flux, flux_err, quality, possible_center, duration_hours, frames=frames)
            if negative is not None:
                negative_center = possible_center
                break
        if negative is None:
            last_reason = "TPF lacks an off-transit control window"
            continue
        selected = (tpf_name, tpf_url, positive, negative, tpf_metadata, positive_center, negative_center)
        break
    if selected is None:
        raise RuntimeError(last_reason)
    return row, selected


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--positive-count", type=int, default=1000)
    parser.add_argument("--frames", type=int, default=16)
    parser.add_argument("--max-hosts", type=int, default=0, help="optional bound; zero means no bound")
    parser.add_argument("--workers", type=int, default=8, help="parallel MAST acquisition workers")
    parser.add_argument("--keep-tpf", action="store_true", help="retain downloaded raw TPFs for audit")
    args = parser.parse_args()
    if args.positive_count < 1 or args.frames < 4 or args.workers < 1:
        raise ValueError("positive-count and workers must be positive, and frames must be at least 4")
    args.output_dir.mkdir(parents=True, exist_ok=True)
    cache_dir = args.output_dir / "listing-cache"
    cache_dir.mkdir(exist_ok=True)
    examples_dir = args.output_dir / "examples"
    examples_dir.mkdir(exist_ok=True)
    raw_dir = args.output_dir / "raw-tpf"
    raw_dir.mkdir(exist_ok=True)

    candidates = _catalog_rows(args.catalog)
    if args.max_hosts:
        candidates = candidates[: args.max_hosts]
    manifest_path = args.output_dir / "corpus_manifest.jsonl"
    report_path = args.output_dir / "corpus_report.json"
    records: list[dict[str, object]] = []
    failures: list[dict[str, str]] = []
    positive_count = 0
    start_time = time.time()

    def write_result(manifest, pair_index: int, row: dict[str, str], selected) -> None:
        tpf_name, tpf_url, positive, negative, tpf_metadata, positive_center, negative_center = selected
        kepid = int(row["kepid"])
        period = float(row["koi_period"])
        epoch = float(row["koi_time0bk"])
        duration_hours = float(row["koi_duration"])
        base_metadata = {
            "catalog": "MAST Kepler KOI DR25 tabdelimited 2017-03-27",
            "catalog_row": row,
            "tpf_url": tpf_url,
            "tpf_metadata": tpf_metadata,
            "published_epoch_bkjd": epoch,
            "published_period_days": period,
            "published_duration_hours": duration_hours,
            "selected_transit_center_bkjd": positive_center,
            "control_center_bkjd": negative_center,
            "label_source": "published confirmed Kepler planet ephemeris; no synthetic injection",
            "positive_window_metrics": _window_metrics(positive),
            "control_window_metrics": _window_metrics(negative),
        }
        for suffix, payload, label, center in (
            ("positive", positive, 1, positive_center),
            ("control", negative, 0, negative_center),
        ):
            filename = f"{pair_index:04d}-{suffix}.npz"
            out_path = examples_dir / filename
            _write_example(
                out_path,
                times=payload[0],
                flux=payload[1],
                flux_err=payload[2],
                quality=payload[3],
                label=label,
                metadata={**tpf_metadata, "tpf_url": tpf_url},
            )
            record = {
                "example_id": f"kepler-dr25-{pair_index:04d}-{suffix}",
                "path": str(out_path.relative_to(args.output_dir)),
                "label": label,
                "label_name": "confirmed_transit" if label else "ephemeris_off_transit_control",
                "target_name": row["kepler_name"],
                "kepid": kepid,
                "kepoi_name": row["kepoi_name"],
                "split": _split_for_host(kepid),
                "center_bkjd": center,
                "provenance": base_metadata,
            }
            manifest.write(json.dumps(record, sort_keys=True) + "\n")
            records.append(record)

    with manifest_path.open("w", encoding="utf-8") as manifest:
        futures: dict[Future, tuple[int, dict[str, str]]] = {}
        with ThreadPoolExecutor(max_workers=args.workers) as executor:
            for candidate_index, row in enumerate(candidates):
                futures[executor.submit(
                    _acquire_candidate,
                    row,
                    cache_dir=cache_dir,
                    raw_dir=raw_dir,
                    keep_tpf=args.keep_tpf,
                    frames=args.frames,
                )] = (candidate_index, row)
            for future in as_completed(futures):
                candidate_index, row = futures[future]
                if positive_count >= args.positive_count:
                    future.cancel()
                    continue
                try:
                    _, selected = future.result()
                    write_result(manifest, positive_count, row, selected)
                    positive_count += 1
                    if positive_count % 25 == 0:
                        print(json.dumps({"positive_pairs": positive_count, "candidate_index": candidate_index}), flush=True)
                except Exception as exc:  # keep acquisition moving across unavailable quarters
                    failures.append({"kepid": row["kepid"], "kepoi_name": row.get("kepoi_name", ""), "error": str(exc)})

    report = {
        "status": "complete" if positive_count >= args.positive_count else "insufficient_examples",
        "positive_pairs": positive_count,
        "total_examples": len(records),
        "positive_examples": sum(int(record["label"]) == 1 for record in records),
        "control_examples": sum(int(record["label"]) == 0 for record in records),
        "candidate_hosts": len(candidates),
        "failures": failures,
        "catalog_sha256": None,
        "catalog": str(args.catalog),
        "created_unix": time.time(),
        "elapsed_seconds": time.time() - start_time,
        "tpf_source": BASE_URL,
        "raw_tpf_retained": args.keep_tpf,
    }
    report["catalog_sha256"] = _sha256(args.catalog)
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({k: report[k] for k in ("status", "positive_pairs", "total_examples", "positive_examples", "control_examples", "elapsed_seconds")}, sort_keys=True))
    return 0 if report["status"] == "complete" else 2


if __name__ == "__main__":
    raise SystemExit(main())
